version: "3.8"

services:
  # Setup database service
  db:
    image: postgres:14.7
    restart: always

    # Set user, password and database name
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Expose port 5432 to the host
    ports:
      - 5432:5432

    # Persist data in the folder "postgres-data"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
